CREATE TABLE shelf_books (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shelf_id       BIGINT NOT NULL,
    book_id        BIGINT NOT NULL,
    added_at       TIMESTAMP,
    reading_status VARCHAR(50) DEFAULT 'NOT_STARTED',
    notes          TEXT,
    CONSTRAINT fk_shelf_books_shelf FOREIGN KEY (shelf_id) REFERENCES bookshelves(id) ON DELETE CASCADE,
    CONSTRAINT fk_shelf_books_book FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE,
    CONSTRAINT uq_shelf_book UNIQUE (shelf_id, book_id)
);

CREATE INDEX idx_shelf_books_shelf_id ON shelf_books (shelf_id);
CREATE INDEX idx_shelf_books_book_id ON shelf_books (book_id);
