CREATE TABLE books (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          VARCHAR(255) NOT NULL,
    author         VARCHAR(255) NOT NULL,
    isbn           VARCHAR(255) UNIQUE,
    description    VARCHAR(1000),
    cover_url      VARCHAR(255),
    published_date DATE,
    category_id    BIGINT,
    CONSTRAINT fk_books_category FOREIGN KEY (category_id) REFERENCES categories(id)
);
