CREATE TABLE wishlist_items (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  BIGINT NOT NULL,
    book_id  BIGINT NOT NULL,
    added_at TIMESTAMP,
    CONSTRAINT fk_wishlist_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_wishlist_book FOREIGN KEY (book_id) REFERENCES books(id)
);
