CREATE TABLE bookshelves (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    position   INTEGER NOT NULL DEFAULT 0,
    user_id    BIGINT NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_bookshelf_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_bookshelves_user_id ON bookshelves (user_id);
CREATE INDEX idx_bookshelves_user_position ON bookshelves (user_id, position);
